GET https://server1-klrg.onrender.com

//                          create
###
GET https://server1-klrg.onrender.com/create?name=majid&email=majid@email.com&password=majid

###
GET https://server1-klrg.onrender.com/create?name=absar&email=absar@email.com&password=absar

###
GET https://server1-klrg.onrender.com/create?name=bilal&email=bilal@email.com&password=bilal

//                          duplicate user
###
GET https://server1-klrg.onrender.com/create?name=majid&email=majid@email.com&password=majid


//                           read all
###
GET https://server1-klrg.onrender.com/all

//                          read
###
GET https://server1-klrg.onrender.com/read?email=majid@email.com


//                          update
###
GET https://server1-klrg.onrender.com/update?name=naeem&email=majid@email.com

//                          delete
###
GET https://server1-klrg.onrender.com/delete?email=majid@email.com

###
GET https://server1-klrg.onrender.com/all

###
GET https://server1-klrg.onrender.comdelete?email=absar@email.com

###
GET https://server1-klrg.onrender.com/all

###
GET https://server1-klrg.onrender.comdelete?email=bilal@email.com

###
GET https://server1-klrg.onrender.com/all




### CATEGORY APIs

# Create a Category
POST http://localhost:8001/api/category/add-category
Content-Type: application/json

{
  "name": "Electronics",
  "description": "Devices and gadgets"
}

### Read All Categories
GET http://localhost:8001/api/category/all-category

### Read a Category
GET http://localhost:8001/api/category/read?name=Groceries

### Update Category
PUT http://localhost:8001/api/category/edit-category
Content-Type: application/json

{
  "name": "Electronics",
  "newName": "Tech Gadgets",
  "description": "Updated category"
}

### Delete Category
DELETE http://localhost:8001/api/category/delete?name=Tech Gadgets

### PRODUCT APIs

# Create a Product
POST http://localhost:8001/api/product/add-product
Content-Type: application/json

{
  "name": "Smartphone",
  "description": "Latest Android device",
  "price": 999,
  "category": "CATEGORY_ID_HERE",
  "quantity": 5
}

### Read All Products
GET http://localhost:8001/api/product/all-product

### Read a Product
POST http://localhost:8001/api/product/single-product
Content-Type: application/json

{
  "name": "check"
}

### Update a Product
POST http://localhost:8001/api/product/edit-product
Content-Type: application/json

{
  "name": "check",
  "newName": "check2",
  "price": 1099
}

### Delete a Product
POST http://localhost:8001/api/product/delete-product
Content-Type: application/json

{
  "name": "Smartphone Pro"
}
